Feature/5
ut-career/reception-frontend pull request #6
Opened 2024-07-25 05:37 UTC by kawashimatakuya117

close #4

2024-07-25 08:09 UTC, moeyashi requested changes

2024-07-25 08:09 UTC, moeyashi commented on src/app/confirm-call-destination/_components/ActionButton.tsx
> +const usesendMessage = (endpoint:string) =>{
```suggestion
const useSendMessage = (endpoint:string) =>{
```

2024-07-25 08:09 UTC, moeyashi commented on src/app/confirm-call-destination/_components/ActionButton.tsx
> +    const response = await fetch(`${ENDPOINT_BASE_PATH}/${endpoint}`, { //バックエンドデプロイ後正しいURLに変更
```suggestion
    const response = await fetch(`${ENDPOINT_BASE_PATH}/${endpoint}`, {
```

2024-07-25 08:09 UTC, moeyashi commented on src/app/confirm-call-destination/_components/ActionButton.tsx
> +      },
これいる？

```suggestion
```

2024-07-25 08:09 UTC, moeyashi commented on src/app/confirm-call-destination/_components/ActionButton.tsx
> +    return NextResponse.json(data)
returnする必要ある？

```suggestion
```

2024-07-26 04:25 UTC, kawashimatakuya117 commented on src/app/confirm-call-destination/_components/ActionButton.tsx
> +    return NextResponse.json(data)
41行目は何となくここでreturnした値をrouter.push等で呼び出し失敗画面にエラーメッセージとしてアラートで表示しようと考えていてreturnしていましたが、それが必要なければreturnする必要もないと思います。
45行目はレスポンスが200なのか401なのかによって呼び出し完了画面と呼び出し失敗画面のどちらに遷移するかを決めようと思っているためreturnするべきかと考えていました。

2024-07-26 04:48 UTC, moeyashi commented on src/app/confirm-call-destination/_components/ActionButton.tsx
> +    return NextResponse.json(data)
OKです。そしたら書きたいです。
また、「エラーメッセージとしてアラートで表示しようと考えていて」や「レスポンスが200なのか401なのかによって呼び出し完了画面と呼び出し失敗画面のどちらに遷移するかを決めよう」はコードにコメントして残しておいて欲しいです。

```suggestion
    if (!response.ok) {
      return { error: 'Failed to send message' , status: response.status }
    }

    const data = await response.json()
    return data
```

2024-07-26 04:51 UTC, kawashimatakuya117 commented on src/app/confirm-call-destination/_components/ActionButton.tsx
> +    return NextResponse.json(data)
承知しました！申し訳ありません。

2024-07-26 05:02 UTC, moeyashi requested changes

2024-07-26 05:02 UTC, moeyashi commented on src/app/confirm-call-destination/_components/ActionButton.tsx
> +      return NextResponse.json({ error: 'Failed to send message', status: response.status })
```suggestion
      return { error: 'Failed to send message', status: response.status }
```

2024-07-29 02:43 UTC, merged